#!/bin/sh
#
# Configurables:
#
#  - Disk size is in GB
#  - Memory size is in MB
#  - SSH port is the local forwarded port to the VM:22
#
disksize="32"
memsize="1024"
sshport="2222"
vmname="SmartOS"
host="https://us-east.manta.joyent.com"


set -e
vboxdir=$(VBoxManage list systemproperties \
            | awk '/^Default.machine.folder/ { print $4 }')

latest_path=$(curl -sk "$host/Joyent_Dev/public/SmartOS/latest")
smartos_version="${latest_path##*/}"
latest_url="${host}${latest_path}"
md5sums_url="$host$latest_path/md5sums.txt"
latest_md5=$(curl -s $md5sums_url | awk "/${smartos_version}.iso/ { print \$1 }")

#
# Download the latest ISO image and verify
#
mkdir -p "${vboxdir}/${vmname}"
if [ ! -f "${vboxdir}/${vmname}/smartos-${smartos_version}.iso" ]; then
  echo "Downloading ${dlsite}/smartos-${smartos_version}.iso"
  curl -o "${vboxdir}/${vmname}/smartos-${smartos_version}.iso" \
          ${latest_url}/smartos-${smartos_version}.iso
  if [[ "$OSTYPE" =~ ^darwin ]]; then
    dl_md5=$(md5 "${vboxdir}/${vmname}/smartos-${smartos_version}.iso" \
             | awk '{ print $4 }')
  else
    dl_md5=$(md5sum "${vboxdir}/${vmname}/smartos-${smartos_version}.iso" \
             | awk '{ print $1 }')
  fi
  if [ -z "${dl_md5}" ]; then
    echo "ERROR: Couldn't fetch ISO image"
    exit 1
  fi
  if [ "${latest_md5}" != "${dl_md5}" ]; then
    echo "ERROR: md5 checksums do not match"
    exit 1
  fi
fi

#
# Create VirtualBox VM
#
echo "Creating/Updating Virtual Machine"
if VBoxManage showvminfo "${vmname}" >/dev/null 2>&1; then
    # VM already exists, just update the ISO image
    VBoxManage storageattach "${vmname}" --storagectl "IDE Controller" \
      --port 1 --device 0 --type dvddrive \
      --medium "${vboxdir}/${vmname}/smartos-${smartos_version}.iso"
else
    # Create the VM
    VBoxManage createvm --name "${vmname}" --ostype OpenSolaris_64 --register
    VBoxManage storagectl "${vmname}" --name "IDE Controller" --add ide
    VBoxManage storagectl "${vmname}" --name "SATA Controller" --add sata

    # Attach the ISO image
    VBoxManage storageattach "${vmname}" --storagectl "IDE Controller" \
      --port 1 --device 0 --type dvddrive \
      --medium "${vboxdir}/${vmname}/smartos-${smartos_version}.iso"

    # Create and attach the zone disk
    VBoxManage createhd --filename "${vboxdir}/${vmname}/smartos-zones.vdi" \
      --size $(echo "${disksize}*1024" | bc)
    VBoxManage storageattach "${vmname}" --storagectl "SATA Controller" \
      --port 0 --device 0 --type hdd \
      --medium "${vboxdir}/${vmname}/smartos-zones.vdi"

    # Set misc settings
    VBoxManage modifyvm "${vmname}" --boot1 dvd --boot2 disk --boot3 none
    VBoxManage modifyvm "${vmname}" --memory ${memsize}
    VBoxManage modifyvm "${vmname}" --natpf1 "SSH,tcp,,${sshport},,22"
fi

#
# Start it up
#
echo "Starting Virtual Machine"
VirtualBox --startvm "${vmname}" &
